name: pennytrack
description: A personal bookkeeping Flutter application.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  shared_preferences: ^2.5.3
  collection: ^1.18.0
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/analyse.png
    - assets/images/me.png
    - assets/images/record.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
